sonar.projectKey=inspectres-vtt
sonar.exclusions=reference/**,foundry/node_modules/**,docs/node_modules/**,.tmp/,foundry/playwright-report/**,.semgrep-results/**
sonar.test.inclusions=**/*.test.ts
sonar.python.version=3.12
sonar.javascript.lcov.reportPaths=foundry/coverage/lcov.info
